### ISSUE TITLE
update Operate CSRF token used in Tests

### ISSUE THREAD

**Issue by houssain-barouni** [camunda/c8-multi-region#94]
With https://github.com/camunda/camunda/pull/19305 , we are changing `OPERATE-X-CSRF-TOKEN` header to `X-CSRF-TOKEN` 

It seems that it is being used in https://github.com/camunda/c8-multi-region/blob/05e88ff715db6195eede4b7f5fae20e5b3aa48d5/test/internal/helpers/kubectl/helpers.go#L139 

We need to switch it to the new header. or use the two headers to support old and new Operate versions

**Comment by Langleu** [comment]
@houssain-barouni thanks for the heads up!
Is this also backported to 8.4 or will there be a difference in the two with 8.4 still using `OPERATE....` and 8.5+ using `X-CSRF...` ?

**Comment by houssain-barouni** [comment]
@Langleu no it will not be backported
8.6+ will be using `X-CSRF-TOKEN`
8.5.X and lower version uses `OPERATE-X-CSRF-TOKEN`
I suggest to parse both headers (`OPERATE-X-CSRF-TOKEN` and default on `X-CSRF-TOKEN`) as it is just for testing
